# Generated by Django 4.1.3 on 2022-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile_alter_account_client_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
